splash = false

wallpaper {
  monitor = DP-1
  path = ~/.config/wallpapers/wallpaper_1.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = ~/.config/wallpapers/wallpaper_2.png
  fit_mode = cover
}
