#!/bin/bash

# Search the entire filesystem for files that contain a target string in their
# names. The matching is case-insensitive.

if (( $# != 1 ))
then
  echo "Invalid arguments" >&2
  exit 2
fi

exec find / -iname "*$1*"
